### PR TITLE
Feedback wanted.

### PR DESCRIPTION
**Pull request by ldulcic**
@mttk @jsnajder 

I opened this pull request so you can comment more easily.  Code requires some additional polishing but the main functionality is done. 

I know you are very busy and don't expect you to write huge reviews, just a glance and a sentence or two of comment is enough :) 

Please comment anything you think is wrong.

### CODE REVIEW

**Comment by aitmlouk** [comment]
The result cannot be reproduced with a small dataset using the same args thresholds!

**Comment by ldulcic** [comment]
@aitmlouk did you check out pre-trained models I provided and tested your assumptions with them?

**Comment by aitmlouk** [comment]
@ldulcic  Yes, the pre-trained models are working perfectly, but after training using the training script, it doesn’t work! the prediction is missy (even with the same args and metadata in pretrained models)

**Comment by ldulcic** [comment]
@aitmlouk Let's move this discussion to issues

**Pull request merged**
